apiVersion: v1
kind: ConfigMap
metadata:
  name: fcj-chatbot-config
data:
  EMBEDDING_MODEL: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  LLM_MODEL: "llama-3.1-8b-instant"
  LLM_TEMPERATURE: "0.1"
  VECTORSTORE_PATH: "vectorstore"
  DATA_PATH: "data"
