apiVersion: v1
kind: Service
metadata:
  name: fcj-chatbot-service
  labels:
    app: fcj-chatbot
spec:
  type: LoadBalancer
  selector:
    app: fcj-chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
    name: http
